### ISSUE TITLE
Simplify Docker

### ISSUE THREAD

**Issue by truthsword** [dendianugerah/reubah#6]
```
services:
  reubah:
    image: ghcr.io/dendianugerah/reubah
    container_name: reubah
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges=true
    ports:
      - "8081:8081"
    restart: unless-stopped
```

It's unlikely the port environmental variable is needed and as such should not appear in the default compose file.

I would expect to see UID and GID variables in future updates.

Excited to see how this develops
